### PR TITLE
WIP: Fix prepare delayInMs

### PR DESCRIPTION
**Pull request by landim**
Fix https://github.com/datastax/simulacron/issues/23

### CODE REVIEW

**Comment by tolbertam** [comment]
One possible concern I have about this is that it isn't clear what should be delayed.  For example someone may use this with the intent that the actual execute of the query is delayed, not the prepare.  I think it would be good to add another field for `prepare_delay_in_ms`, wdyt?

**Comment by tolbertam** [comment]
Hrmm, I think this is a use case problem in general.  The current design is that the `then` part only really applies to the `execute` method, not so much the prepare itself.  I.e. you can't prime something that throws an error on the prepare part of things.  maybe a separate section, like a `prepare_then` or something weird could be called for, or just another way to prime `prepare` response behavior separately.

**Comment by landim** [comment]
I will work on the prepare_then approach, I think makes more sense in this case.

**Comment by tolbertam** [comment]
This will be fixed by #31, if `ignore_on_prepare` is false, delay will be considered.

**Pull request closed without merging**
